### ISSUE TITLE
Not work at a new IDE 1.6.12

### ISSUE THREAD

**Issue by pauloeduardosp** [me-no-dev/EspExceptionDecoder#13]
After a upgrade to new ide 1.6.12 decoder stop to work.
When I will open a decoder windown I receive this msg

ERROR: neither Varanda_Des.ino.elf or Varanda_Des.cpp.elf were found!
Did you forget to compile the sketch?

But i already compile and make a sketch upload

**Comment by thiagodasilva** [comment]
I also ran into this issue, but I found a work around for now...

Arduino builds your sketch at a location like /tmp/arduino_build_XXXX
EspExceptionDecoder creates a directory at /tmp/build<somehash>.tmp
It is looking for those files in that directory, so copy all the files from the /tmp/arduino_build_XXX to the temp EspExceptionDecoder directory and you should be able to open the Exception window

**Comment by pauloeduardosp** [comment]
tks for the answer,
i'll try and send you a feedback.

**Comment by electronicsguy** [comment]
Yup, doesn't work OOTB with the new IDE. Hopefully it'll be fixed soon. 

btw, in Windows, the correct paths are:
copy all files from "C:\Users\<username>\AppData\Local\Temp\arduino_build_NNNN\" to "C:\Users\<username>\AppData\Local\Temp\buildNNNNN.tmp\"

Where NNNN are random numbers.

**Comment by danielcbit** [comment]
can some one point to the correct paths at Mac OS?
Tried to create a /tmp/build.tmp folder and copy the build contents from /var/folders/8l/<hash>/T/arduino_build_NNNN.
Also tried to create a arduino_build_NNNN folder at same path where the Arduino IDE is building and copy this same folder to tmp.

Still no success...

**Comment by mph070770** [comment]
I couldn't get the workaround to work. What version of IDE should I revert to if I want to get this working?

**Comment by gfoiani** [comment]
Every time you restart Arduino IDE it builds the sketch in a folder with a different build number:
i.e. `/var/folders/8s/6k3r4rt57r38rl8r4ngd6j780000gn/T/arduino_build_XXXXX/`

I can get it work on Mac OS by linking the built sketch in the folder where the Exception Decoder looks for it, in this way:

`ln -s /var/folders/8s/6k3r4rt57r38rl8r4ngd6j780000gn/T/arduino_build_XXXXX/MySketch.ino.elf /var/folders/8s/6k3r4rt57r38rl8r4ngd6j780000gn/T/build9d362461b273ac7cd349f8fd844f1118.tmp/MySketch.ino.elf`

where XXXXX is the build number that changes every time you restart Arduino IDE. So you have to run this command every time you restart Arduino IDE checking in advance which is the new build number.

**Comment by me-no-dev** [comment]
FIXED!
please download latest release

**Comment by pickeld** [comment]
hey . i did download the latest release. still get the error. 
ERROR: neither testjason.ino.elf or testjason.cpp.elf were found!
Did you forget to compile the sketch?

**Comment by me-no-dev** [comment]
not possible :) did you restart the IDE? which version did you download?

**Comment by pickeld** [comment]
im using Arduino IDE Version 1.6.12
and EspExeptionDecoder Version 1.0.6
Ive extracted the jar file into this location:
C:\Users\David\Documents\Arduino\tools\EspExceptionDecoder\tool\EspExceptionDecoder.jar
restarted the Arduino IDE opened the SerialMonitor, uploaded my sketch, got the error on the serial monitor. then when i pressed ESP Exception Decder i see on screen 


`Uploading 233344 bytes from C:\Users\David\AppData\Local\Temp\arduino_build_182492/testjson.ino.bin to flash at 0x00000000
................................................................................ [ 35% ]
................................................................................ [ 70% ]
....................................................................             [ 100% ]
ERROR: neither testjson.ino.elf or testjson.cpp.elf were found!
Did you forget to compile the sketch?`

**Comment by pickeld** [comment]
im so sorry, i kept an old version on other location . seems like i saved the new one in the wrong location.
this issue is Solved.
thank you for the hard work!

**Comment by me-no-dev** [comment]
glad it works :)
